package com.bit_etland.web.enums;

public enum Action {
	MOVE,LOGIN,REGISTER,ACCESS,SIGNUP,SIGNIN,CUS_LIST,CUST_RETRIEVE
	, CUS_UPDATE, CUS_FILE_UPLOAD, CUST_DELETE, PRO_LIST, PRO_REGIST, PRO_UPDATE, CATE_LIST,
}
